In [14]:
import pandas as pd
import numpy as np
import random

output_1 = pd.read_csv('output (1).csv')
output_2 = pd.read_csv('output (2).csv')
output_3 = pd.read_csv('output (3).csv')

valid_datas = len(output_1)
classes = 42
predict = []

for i in range(valid_datas) :
    arr = np.zeros(42)
    
    arr[output_1.iloc[i].item()] += 1
    arr[output_2.iloc[i].item()] += 1
    arr[output_3.iloc[i].item()] += 1
    
    max_index = np.where(arr == arr.max())
    print(max_index)
    
    if len(max_index[0]) == 1 :
        if output_1.iloc[i].item() != max_index[0][0] :
            print('2, 3 => ', max_index[0][0])
        predict.append(max_index[0][0])
    else : 
        if output_1.iloc[i].item() in max_index[0] :
            print('1 => : ', output_1.iloc[i].item())
            predict.append(output_1.iloc[i].item())
        elif output_2.iloc[i].item() in max_index[0] :
            print('2 => : ', output_1.iloc[i].item())
            predict.append(output_2.iloc[i].item())
        else :
            c = random.choice(max_index[0])
            print(i, max_index[0], ' : ', c, arr[c])
            predict.append(arr[c])
        
out = pd.DataFrame(predict, columns = ['pred'])
out.to_csv('hard_vote_over_74.csv', index = False)

(array([2]),)
(array([10]),)
(array([8]),)
2, 3 =>  8
(array([0]),)
(array([0]),)
(array([33]),)
(array([7]),)
2, 3 =>  7
(array([0]),)
(array([4]),)
(array([20]),)
(array([0]),)
(array([0]),)
(array([0]),)
(array([8]),)
2, 3 =>  8
(array([0, 1, 5]),)
1 => :  1
(array([0]),)
(array([0]),)
(array([11]),)
(array([0]),)
(array([10]),)
2, 3 =>  10
(array([15]),)
(array([0]),)
(array([0]),)
(array([27]),)
(array([7]),)
2, 3 =>  7
(array([4]),)
(array([10]),)
2, 3 =>  10
(array([0]),)
(array([0]),)
(array([0]),)
2, 3 =>  0
(array([0]),)
(array([4]),)
(array([12]),)
(array([ 0,  8, 11]),)
1 => :  11
(array([23]),)
(array([0]),)
(array([21]),)
(array([4]),)
2, 3 =>  4
(array([10]),)
(array([22]),)
(array([0, 1, 8]),)
1 => :  1
(array([0]),)
2, 3 =>  0
(array([10]),)
2, 3 =>  10
(array([25]),)
(array([17]),)
(array([2]),)
(array([9]),)
2, 3 =>  9
(array([2]),)
(array([0]),)
(array([15]),)
(array([0]),)
2, 3 =>  0
(array([10]),)
(array([0]),)
(array([2]),)
(array([0]),)
(array([15]),)
(array([39

In [16]:
import numpy as np
arr = np.array([1, 2, 3, 3])
occurences = np.where(arr == arr.max())
print(occurences)

(array([2, 3]),)


In [3]:
print('전체 용량')
!df -h

print('\n\n내가 사용중인 용량')
!du -h --max-depth=1 | sort -hr


import torch, sklearn, gc
print('\ntorch 캐시 삭제')
torch.cuda.empty_cache()
print('sklearn 캐시 삭제')
#sklearn.datasets.clear_data_home()
print('GC 가동')
gc.collect()
print('휴지통 삭제')
!cd ~
!rm -r ./.local/share/Trash/files

print('\n전체 용량')
!df -h

print('\n\n내가 사용중인 용량')
!du -h --max-depth=1 | sort -hr

전체 용량
Filesystem      Size  Used Avail Use% Mounted on
overlay          99G   81G   14G  86% /
tmpfs            64M     0   64M   0% /dev
tmpfs            30G     0   30G   0% /sys/fs/cgroup
shm             1.0G   16K  1.0G   1% /dev/shm
/dev/xvdb1       99G   81G   14G  86% /etc/hosts
tmpfs            30G   12K   30G   1% /proc/driver/nvidia
/dev/xvda1       48G  9.1G   36G  21% /usr/bin/nvidia-smi
udev             30G     0   30G   0% /dev/nvidia0
tmpfs            30G     0   30G   0% /proc/acpi
tmpfs            30G     0   30G   0% /proc/scsi
tmpfs            30G     0   30G   0% /sys/firmware


내가 사용중인 용량
60K	.
12K	./.ipynb_checkpoints

torch 캐시 삭제
sklearn 캐시 삭제
GC 가동
휴지통 삭제
rm: cannot remove './.local/share/Trash/files': No such file or directory

전체 용량
Filesystem      Size  Used Avail Use% Mounted on
overlay          99G   81G   14G  86% /
tmpfs            64M     0   64M   0% /dev
tmpfs            30G     0   30G   0% /sys/fs/cgroup
shm             1.0G   16K  1.0G   1% /dev/shm